### ISSUE TITLE
signalrMock doesn't allow lifecycle events

### ISSUE THREAD

**Issue by johnmccollum** [basslagter/cypress-plugin-signalr#1]
Hi, thanks for the library - it's really useful!

In our application, we're doing something like this:

```js
connection.onreconnecting(handlers.reconnecting)
```

(Where `connection` is either from `new signalR.HubConnectionBuilder()` or `window.signalrMock`, depending on whether the latter exists.)

Unfortunately it looks like `signalrMock` doesn't have lifecycle events built in, so when we try the above line of code, there's an error because `onreconnecting` doesn't exist.

We're resolving the problem like this at the moment:

```js
signalrMock.start = () => Promise.resolve()
signalrMock.onreconnecting = () => {}
// and so on
```

Is this the best approach? Would it be possible to add these to the library?

**Comment by basslagter** [comment]
Hi John,

Thanks for the report. I will look into it!

**Comment by basslagter** [comment]
Hi John.

When I look at the HubConnection definition I can only see these methods:

```
start(): Promise<void>;
stop(): Promise<void>;
stream<T = any>(methodName: string, ...args: any[]): IStreamResult<T>;
send(methodName: string, ...args: any[]): Promise<void>;
invoke<T = any>(methodName: string, ...args: any[]): Promise<T>;
on(methodName: string, newMethod: (...args: any[]) => void): void;
off(methodName: string): void;
off(methodName: string, method: (...args: any[]) => void): void;
onclose(callback: (error?: Error) => void): void;
```

Where currently only on, invoke and onclose are implemented in the cypress plugin.
I can add the other methods as well but I do not see the 'onreconnecting" method as part of the HubConnection. Are you sure?

**Comment by johnmccollum** [comment]
Hi there, thanks for looking into that! 

Yes, we're connecting to a number of lifecycle events defined here:

https://docs.microsoft.com/en-us/javascript/api/@microsoft/signalr/hubconnection?view=signalr-js-latest#methods

**Comment by johnmccollum** [comment]
I've just had a thought - are you perhaps looking at / supporting the @aspnet/signalr package rather than the @microsoft/signalr package?

**Comment by basslagter** [comment]
That is correct. Is the @aspnet package deprecated or such?

**Comment by johnmccollum** [comment]
I'm not sure - it's confusing 😆 

My understanding - which could very well be wrong - is that @aspnet/signalr is for the full .NET framework version, whereas @microsoft/signalr is the .NET Core version.

There is a large warning at the top of the page here:

https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-net-client

...but it only warns you that "this isn't the latest version of the package". Not that it's deprecated. Both versions are on NPM, so I'm really not sure what their official position is.

**Comment by basslagter** [comment]
Ah yes, I recall the confusion I had on this point also. I used this @aspnet client version on a .net core 'backend' with succes but I also see that the @microsoft version is more recently maintained.

**Comment by basslagter** [comment]
@johnmccollum this thread has been silent. Still need help?

**Comment by johnmccollum** [comment]
Well, the application we've written works fine with the hack we've put in place. 

I suppose the question is whether you wanted cypress-plugin-signalr to support the lifecycle events from @microsoft/signalr? If you did, I would be happy to submit a PR.

Alternatively, we might in the future look at forking your repo and maintaining a version for @microsoft/signalr, assuming you're comfortable with that. (I don't see a license in the repo other than the ISC license in the package.json - that's the default, right? I assume you don't want to change it?)

**Comment by basslagter** [comment]
I think there is a big overlap and at this point I don't see a reason to exclude one or the other. In the end it is just a mock after. If you can make a PR that would be great!

Forking is also no problem.
