### ISSUE TITLE
Support without cypress

### ISSUE THREAD

**Issue by milkshakeuk** [basslagter/cypress-plugin-signalr#12]
Is there any way you could export the modules so this could be used without cypess?

**Comment by milkshakeuk** [comment]
I have managed to do it using this syntax but it would be nice if they were exported somehow from the npm module:

```typescript
import { SignalRMock } from 'cypress-plugin-signalr/dist/src/SignalRMock';
import { publish } from 'cypress-plugin-signalr/dist/src/api';
...
```

**Comment by basslagter** [comment]
Sounds like a good idea. Can you make a pr?
